project:
  type: website

website:
  title: "ReneWelch.me"
  navbar:
    right:
      - blog.qmd
      # - publications.qmd
      - talks.qmd
      - software.qmd
      - CV

format:
  html:
    theme: sandstone
    css: styles.css

site-url: www.renewelch.me

