project:
  type: website
  render:
    - ./*.qmd
    - posts/*/index.qmd
    - posts/*/index.md
    - talks/*/index.qmd
    - talks/*/index.md
    - software/*/index.qmd
    - software/*/index.md

website:
  title: "ReneWelch.me"
  navbar:
    right:
      - blog.qmd
      # - publications.qmd
      - talks.qmd
      - software.qmd
      - CV

format:
  html:
    theme: sandstone
    css: styles.css

site-url: www.renewelch.me

